# +-----------------------------------------------------
# |         SPRING DATASOURCE CONFIG
# +-----------------------------------------------------
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_EMPLOYEES_HOST:localhost}:${DB_EMPLOYEES_HOST:33060}/${DB_EMPLOYEES_NAME:employees}
    username: ${DB_EMPLOYEES_USERNAME:employees}
    password: ${DB_EMPLOYEES_PASSWORD:a56e7535-fde4-419b-8556-fd6736e22254}

# +-----------------------------------------------------
# |         SPRING LOGGIN CONFIG
# +-----------------------------------------------------
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.client.RestTamplate: DEBUG
    org.springframework.data.r2dbc: DEBUG
    co.com.merdadolibre.challenge: DEBUG
  pattern:
    console: "%d{yyyy-MMM-dd HH:mm:ss a} [%t] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"