# +--------------------------------------------------
# | CREATE NAMESPACES FOR DIFERENTS ENVIRONMENT
# | AUTHOR: WORTIZ
# | DATE: 09-01-2022
# +--------------------------------------------------

apiVersion: v1
kind: Namespace
metadata:
  name: ns-development
  labels:
    owner: taa
    env: dev
    type: backend
    app: api-employees
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-production
  labels:
    owner: taa
    env: prd
    type: backend
    app: api-employees