# +--------------------------------------------------
# | CREATE RESOURCE QUOTA FOR DIFERENTS ENVIRONMENT
# | AUTHOR: WORTIZ
# | DATE: 09-01-2022
# +--------------------------------------------------

apiVersion: v1
kind: ResourceQuota
metadata:
  name: rq-development
  namespace: ns-development
  labels:
    owner: taa
    env: dev
    type: backend
    app: api-employees
spec:
  hard:
    requests.cpu: "500m"
    requests.memory: "500m"
    limits.cpu: "1"
    limits.memory: "990mi"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: rq-production
  namespace: ns-production
  labels:
    owner: taa
    env: dev
    type: backend
    app: api-employees
spec:
  hard:
    request.cpu: "1"
    request.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi