# +--------------------------------------------------
# | CREATE CONFIG MAPS FOR DIFERENTS ENVIRONMENT
# | AUTHOR: WORTIZ
# | DATE: 09-01-2022
# +--------------------------------------------------

apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-application-development
  namespace: ns-development
  labels:
    owner: taa
    env: dev
    type: configuration
data:
  KEY_DB_EMPLOYEES_HOST: localhost
  KEY_DB_EMPLOYEES_PORT: 33061
  KEY_DB_EMPLOYEES_NAME: employees
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-application-production
  namespace: ns-production
  labels:
    owner: taa
    env: prd
    type: configuration
data:
  KEY_DB_EMPLOYEES_HOST: localhost
  KEY_DB_EMPLOYEES_PORT: 33061
  KEY_DB_EMPLOYEES_NAME: employees