# +--------------------------------------------------
# | CREATE RESOURCE QUOTA FOR DEVELOP ENVIRONMENT
# | AUTHOR: WORTIZ
# | DATE: 09-01-2022
# +--------------------------------------------------

apiVersion: v1
kind: ResourceQuota
metadata:
  name: rq-development
  namespace: ns-development
  labels:
    owner: taa
    env: dev
    type: configuration
    app: api-employees
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi