apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-development
  namespace: ns-development
  labels:
    app: api-employees
    owner: taa
    env: dev
    type: configuration
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.2
  nfs:
    server: nfs-server
    path: "/mnt/nfs_server"