apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-development
  namespace: ns-development
  labels:
    app: api-employees
    owner: taa
    env: prd
    type: configuration
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi