# +--------------------------------------------------
# | CREATE CONFIG MAPS FOR DEVELOPMENT ENVIRONMENT
# | AUTHOR: WORTIZ
# | DATE: 09-01-2022
# +--------------------------------------------------

apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-application-development
  namespace: ns-development
  labels:
    owner: taa
    env: dev
    type: configuration
    app: api-employees
data:
  KEY_APP_ENVIRONMENT: dev
  KEY_APP_FILESYSTEM: /employee/dev/data
  KEY_DB_EMPLOYEES_HOST: svc-mysql-server-development
  KEY_DB_EMPLOYEES_PORT: "33060"
  KEY_DB_EMPLOYEES_NAME: employees