# +--------------------------------------------------
# | CREATE DEPLOYMENT FOR DEVELOPMENT ENVIRONMENT
# | AUTHOR: WORTIZ
# | DATE: 10-01-2022
# +--------------------------------------------------

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dlt-api-employees
  namespace: ns-development
  labels:
    owner: taa
    env: dev
    type: application
    app: api-employees
spec:
  selector:
    matchLabels:
      owner: taa
      env: dev
      type: application
      app: api-employees
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  replicas: 1
  template:
    metadata:
      labels:
        owner: taa
        env: dev
        type: application
        app: api-employees
    spec:
      restartPolicy: Always
      volumes:
        - name: vlm-dev-nfs-storage
          persistentVolumeClaim:
            claimName: pvc-development
      containers:
        - name: employee-services
          image: wortiz1027/employee-services:v1.0.4-20220116161801
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
            - name: monitor
              containerPort: 9090
          env:
            - name: APP_FYLESYSTEM
              valueFrom:
                configMapKeyRef:
                  name: cm-application-development
                  key: KEY_APP_FILESYSTEM
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: cm-application-development
                  key: KEY_APP_ENVIRONMENT
            - name: DB_EMPLOYEES_HOST
              valueFrom:
                configMapKeyRef:
                  name: cm-application-development
                  key: KEY_DB_EMPLOYEES_HOST
            - name: DB_EMPLOYEES_PORT
              valueFrom:
                configMapKeyRef:
                  name: cm-application-development
                  key: KEY_DB_EMPLOYEES_PORT
            - name: DB_EMPLOYEES_NAME
              valueFrom:
                configMapKeyRef:
                  name: cm-application-development
                  key: KEY_DB_EMPLOYEES_NAME
            - name: DB_EMPLOYEES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: sc-db-credential-development
                  key: KEY_DB_EMPLOYEES_USERNAME
            - name: DB_EMPLOYEES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sc-db-credential-development
                  key: KEY_DB_EMPLOYEES_PASSWORD
          volumeMounts:
            - name: vlm-dev-nfs-storage
              mountPath: "/employee/dev/data"
          resources:
            requests:
              memory: "100Mi"
              cpu: "250m"
            limits:
              memory: "150Mi"
              cpu: "350m"
#          readinessProbe:
#            initialDelaySeconds: 200
#            timeoutSeconds: 5
#            httpGet:
#              path: /monitor/actuator/health/readiness
#              port: 9090
#          livenessProbe:
#            initialDelaySeconds: 200
#            timeoutSeconds: 10
#            failureThreshold: 10
#            periodSeconds: 5
#            httpGet:
#              path: /monitor/actuator/health/liveness
#              port: 9090
#          startupProbe:
#            httpGet:
#              path: /ping
#              port: 8080
#            failureThreshold: 30
#            periodSeconds: 10