# +--------------------------------------------------
# | CREATE NAMESPACES FOR PRODUCTION ENVIRONMENT
# | AUTHOR: WORTIZ
# | DATE: 09-01-2022
# +--------------------------------------------------

apiVersion: v1
kind: Namespace
metadata:
  name: ns-production
  labels:
    owner: taa
    env: prd
    type: configuration
    app: api-employees