# +---------------------------------------------------------------------
# | CREATE SERVICE CONNECT TO EXTERNAL MYSQL FOR PRODUCTION ENVIRONMENT
# | AUTHOR: WORTIZ
# | DATE: 09-01-2022
# +---------------------------------------------------------------------

apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: ns-development
  labels:
    app: api-employees
    owner: taa
    env: prd
    type: configuration
spec:
  ports:
    - name: "mysql"
      protocol: "TCP"
      port: 3306
      targetPort: 3306
      nodePort: 0
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mysql
  namespace: ns-development
  labels:
    app: api-employees
    owner: taa
    env: prd
    type: configuration
subsets:
  - addresses:
      - ip: 192.168.59.107
    ports:
      - port: 33061
        name: "mysql"