apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-production
  namespace: ns-production
  labels:
    app: api-employees
    owner: taa
    env: prd
    type: configuration
spec:
  capacity:
    storage: 3Gi
  volumeMode: FileSystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.2
  nfs:
    server: 192.168.59.104
    path: "/mnt/nfs_server"