apiVersion: v1
kind: PersistentVolumeClaim
metada:
  name: pvc-production
  namespace: ns-production
  labels:
    app: api-employees
    owner: taa
    env: prd
    type: configuration
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi