# +--------------------------------------------------
# | CREATE CONFIG MAPS FOR PRODUCTION ENVIRONMENT
# | AUTHOR: WORTIZ
# | DATE: 09-01-2022
# +--------------------------------------------------

apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-application-production
  namespace: ns-production
  labels:
    owner: taa
    env: prd
    type: configuration
    app: api-employees
data:
  KEY_APP_ENVIRONMENT: prd
  KEY_APP_FYLESYSTEM: /employee/prd/data
  KEY_DB_EMPLOYEES_HOST: developer-io
  KEY_DB_EMPLOYEES_PORT: "33061"
  KEY_DB_EMPLOYEES_NAME: employees