# +--------------------------------------------------
# | CREATE SERVICE FOR PRODUCTION ENVIRONMENT
# | AUTHOR: WORTIZ
# | DATE: 10-01-2022
# +--------------------------------------------------

apiVersion: v1
kind: Service
metadata:
  name: svc-employee-services-production
  namespace: ns-production
  labels:
    owner: taa
    env: dev
    type: application
    app: api-employees
spec:
  selector:
    owner: taa
    env: dev
    type: application
    app: api-employees
  type: NodePort
  ports:
    - name: http
      port: 8081
      targetPort: 8080
    - name: http
      port: 9091
      targetPort: 9090